<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
<head id="ctl00_Head1">
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<meta content="" http-equiv="keywords"/>
<meta content="" http-equiv="description"/>
<meta content="15 Feb 2024 10:53:12 AEDT" http-equiv="Last-Modified"/><meta content="rural-security" name="title"/>

<link href="https://www.commbank.com.au//etc/designs/default/favicon.ico" rel="icon" type="image/vnd.microsoft.icon"/>
<link href="https://www.commbank.com.au//etc/designs/default/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon"/>
<title>rural-security</title>
<link href="https://www.commbank.com.au//etc/designs/commbroker/clientlibs_base/css/menu.css" rel="stylesheet" type="text/css"/>
<link href="https://www.commbank.com.au//etc/designs/commbroker/clientlibs_base/css/layout.css" rel="stylesheet" type="text/css"/>
<link href="https://www.commbank.com.au//etc/designs/commbroker/clientlibs_base/css/styles.css" rel="stylesheet" type="text/css"/>
<link href="https://www.commbank.com.au//etc/designs/commbroker/clientlibs_base/css/MenuPrint.css" media="print" rel="stylesheet" type="text/css"/>
<link href="https://www.commbank.com.au//etc/designs/commbroker/clientlibs_base/css/layoutPrint.css" media="print" rel="stylesheet" type="text/css"/>




<!-- SiteCatalyst code version: H.20.3.Copyright 1996-2009 Adobe, Inc. All Rights ReservedMore info available at http://www.omniture.com -->


</head>
<body>
<general>
<div id="Container">
<content>
<div id="wrapper">
<div id="content" style="position:relative;">
<div class="page_heading">
<page_heading>
<h1 class="title">Credit Policy</h1>
</page_heading>
</div>
<div class="subheading">
<sub_heading>
<h1>Rural Residential Property</h1>
</sub_heading>
</div>
<div class="text parbase">
<p style="text-align: right;"><span style="font-size: 10pt;"><a href="/Net/Documentum/credit-policy/satisfactory-security.aspx">Back to Satisfactory Security</a></span></p>
<p><span style="font-size: 10pt;"> </span></p>
<p><span style="font-size: 10pt;"> </span></p>
<table border="1" cellpadding="1" cellspacing="0">
<tbody>
<tr>
<th scope="col" width="50%"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Acceptable Rural Residential Property </span></span></th>
<th scope="col"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Criteria</span></span></th>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 9pt;">Rural properties up to 50 hectares with a completed dwelling</span></span></td>
<td>
<ul>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Must have a dwelling on it and be zoned by the local government for residential occupancy</span></span></li>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Required to be connected to all normal services (i.e. water, sewerage, electricity etc.)<br/> </span></span></li>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Property must be fully accessible with legal access<br/> </span></span></li>
<li><span style="font-size: 10pt;">Income generated by the property (total turnover/sales) <b>cannot exceed 25%</b> of the total other eligible income included in the application<br/> </span></li>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Income from the property can be utilised in servicing including addbacks (e.g. interest and depreciation), any losses (if applicable) must also be included<br/> </span></span></li>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Income from the property must be verified as part of the current Eligible Income (i.e. <b>Self Employed, Rental Income</b><br/> </span></span></li>
</ul> <p><span style="font-size: 10pt;"><span style="font-size: 9pt;"><b>Notes:</b></span></span></p>
<ul>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">External valuation is required. Valuation must be ordered through CommVal or manually via the Credit Team where CommVal does not allow you to order<br/> </span></span></li>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Property is to be valued on the basis of house and land only (i.e. not a ‘going concern’ or ‘in use’ value).<br/> </span></span></li>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Valuation must evidence property is within permitted use rights i.e. can have a residential dwelling<br/> </span></span></li>
</ul> </td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 9pt;">Rural properties in excess of 50 hectares and up to a maximum of 100 hectares may be considered as an <b>exception </b>by Credit where the following criteria have been met<br/> </span></span></td>
<td>
<ul>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">In addition to the above criteria; the </span></span></li>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">LVR against the proposed property does not exceed 70%<br/> </span></span></li>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Can only be used for owner occupied purposes<br/> </span></span></li>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Not acceptable for loans with LMI or LDP<br/> </span></span></li>
</ul> </td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 9pt;">Rural properties up to 50 hectares with vacant land<br/> </span></span></td>
<td>
<ul>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Property is zoned by the local government for domestic occupation<br/> </span></span></li>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Loan repayment capacity is not dependent upon income generated from the property<br/> </span></span></li>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Land is devoid of any improvements<br/> </span></span></li>
</ul> <p><span style="font-size: 10pt;"><span style="font-size: 9pt;"><b>Notes:</b></span></span></p>
<ul>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">External valuation is required. Valuation must be ordered through CommVal or manually via the Credit Team where CommVal does not allow you to order</span></span></li>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Property is to be valued on the basis of land only (i.e. not a ‘going concern’ or ‘in use’ value)<br/> </span></span></li>
<li><span style="font-size: 10pt;"><span style="font-size: 9pt;">Vacant land size greater than 11 hectares is unacceptable security for loans with LMI or LDP.<br/> </span></span></li>
</ul> </td>
</tr>
</tbody>
</table>
<p><span style="font-size: 10pt;"> </span></p>
<p><span style="font-size: 10pt;"><b><span style="font-size: 12pt;"><span style="font-size: 11pt;"><span style="font-size: 14pt;">Determining whether the total turnover/total sales is greater than 25% of the other household income (determine security eligibility)</span></span></span></b></span></p>
<table border="1" cellpadding="1" cellspacing="0">
<tbody>
<tr>
<th scope="col" width="10%"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Step</span></span></th>
<th scope="col"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Action</span></span></th>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">1</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Review the <b>most recent</b> financials evidencing income generated from the property.</span></span></td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">2</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Determine the total turnover/total sales (before expenses) from the financials.</span></span></td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">3</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Determine the total other eligible household income used in the application.</span></span></td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">4</span></span></td>
<td>
<table border="1" cellpadding="1" cellspacing="0">
<tbody>
<tr>
<th scope="col"><span style="font-size: 10pt;"><span style="font-size: 14pt;">If...</span></span></th>
<th scope="col"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Then...</span></span></th>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Percentage is 25% or less</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">The property is eligible</span></span></td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Percentage is greater than 25%</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">The property is not eligible under this process but can still be considered as a secondary security</span></span></td>
</tr>
</tbody>
</table> </td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">5</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">End of process.</span></span></td>
</tr>
</tbody>
</table>
<p><span style="font-size: 10pt;"><b><br/> <span style="font-size: 12pt;"><span style="font-size: 14pt;">Examples:</span></span></b></span></p>
<table border="1" cellpadding="1" cellspacing="0">
<tbody>
<tr>
<th scope="col" width="25%"><span style="font-size: 10pt;"> </span></th>
<th scope="col"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Example 1</span></span></th>
<th scope="col"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Example 2</span></span></th>
<th scope="col"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Example 3</span></span></th>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Income - PAYG</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">$100,000<br/> </span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">$100,000</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">$100,000</span></span></td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Rental income (from another property</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">$11,800</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">$11,800</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">$11,800</span></span></td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Turnover from property</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">$10,000</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">$20,000</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">$40,000</span></span></td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Percentage of turnover from the property over other eligible income</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">10,000/(100,000+<br/> 11800)= 8.94%</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">20,000/(100,000+<br/> 11,800)= 17.89%</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">40,000/(100,000+<br/> 11,800)= 35.78%</span></span></td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Acceptable security?</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Yes</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Yes</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">No</span></span></td>
</tr>
</tbody>
</table>
<p><span style="font-size: 10pt;"> </span></p>
<p><span style="font-size: 10pt;"><b><span style="font-size: 11pt;"><span style="font-size: 14pt;">Determine when income generated from the property is to be considered for servicing purposes</span></span></b></span></p>
<p><span style="font-size: 10pt;"><span style="font-size: 12pt;"><b>Note:</b> Income generated from the property which is used for servicing purposes must be from the customer’s own business/es.</span></span></p>
<table border="1" cellpadding="1" cellspacing="0">
<tbody>
<tr>
<th scope="col" width="25%"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Security type</span></span></th>
<th scope="col" width="25%"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Rental income</span></span></th>
<th scope="col" width="25%"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Income generated from the property</span></span></th>
<th scope="col"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Apply net losses</span></span></th>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 12pt;">New/Purchase property</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 12pt;">Yes</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 12pt;">No*</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 12pt;">No*</span></span></td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 12pt;">Existing/proposed property where the applicant has generated income</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 12pt;">Yes</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 12pt;">Yes**</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 12pt;">Yes</span></span></td>
</tr>
</tbody>
</table>
<p><span style="font-size: 10pt;"><span style="font-size: 10pt;">*where the business has been run by the applicants who are now looking to purchase the property. In this scenario, where the property has recorded a net loss, the loss would have to be included in the application.</span></span></p>
<p><span style="font-size: 10pt;"><span style="font-size: 10pt;">**Where the customer confirms their intention is to continue the income generating activity attached to the land.</span></span></p>
<p><span style="font-size: 10pt;"><span style="font-size: 10pt;">The income used for servicing purposes must be the net profit/loss position (i.e. after expenses). To determine the net profit/loss position, follow the <a adhocenable="false" href="/Net/Documentum/credit-policy/eligible-income/self-employed-excludes-low-doc.aspx" target="_blank">Self-Employed (full verification)</a> process.</span></span></p>
<p><span style="font-size: 10pt;"><span style="font-size: 10pt;">It is not always necessary to utilise the net profit generated from the property for servicing purposes however where there is a net loss recorded in the applicant’s financials, the loss must always be recorded.</span></span></p>
<p><span style="font-size: 10pt;"><b><span style="font-size: 14pt;">Examples:</span></b></span></p>
<table border="1" cellpadding="1" cellspacing="0">
<tbody>
<tr>
<th scope="col" width="33%"><span style="font-size: 10pt;"> </span></th>
<th scope="col"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Example 1</span></span></th>
<th scope="col"><span style="font-size: 10pt;"><span style="font-size: 14pt;">Example 2</span></span></th>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Income – PAYG</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">$100,000</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">$100,000</span></span></td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Property Income (NPBT + Addbacks)</span></span></td>
<td><p><span style="font-size: 10pt;"><span style="font-size: 10pt;">Income: $10,000<br/> Expenses: $2,000</span></span></p> <p><span style="font-size: 10pt;"><span style="font-size: 10pt;">NPBT: $8,000</span></span></p> </td>
<td><p><span style="font-size: 10pt;"><span style="font-size: 10pt;">Income: $20,000<br/> Expenses: $25,000</span></span></p> <p><span style="font-size: 10pt;"><span style="font-size: 10pt;">NPBT: (-$5,000)</span></span></p> </td>
</tr>
<tr>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">Income for servicing</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">$108,000</span></span></td>
<td><span style="font-size: 10pt;"><span style="font-size: 10pt;">$95,000</span></span></td>
</tr>
</tbody>
</table>
<p><span style="font-size: 10pt;"> </span></p>
<p> </p>
</div>
<div class="contactsTableBoxLeft">
<div class="text parbase">
</div>
</div>
<div class="contactsTableBoxRight">
<div class="text parbase">
</div>
</div>
</div>
</div>
</content>
</div>
</general>
</body>
</html>
