# Enable automatic processing of md files
markdown: GFM

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Policy Pal
show_downloads: false
site.github.is_project_page: false
github.is_project_page: false
is_project_page: false
