<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
<head id="ctl00_Head1">
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<meta content="" http-equiv="keywords"/>
<meta content="" http-equiv="description"/>
<meta content="1 Feb 2024 11:05:18 AEDT" http-equiv="Last-Modified"/><meta content="proposed-investment-income" name="title"/>

<link href="https://www.commbank.com.au//etc/designs/default/favicon.ico" rel="icon" type="image/vnd.microsoft.icon"/>
<link href="https://www.commbank.com.au//etc/designs/default/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon"/>
<title>proposed-investment-income</title>
<link href="https://www.commbank.com.au//etc/designs/commbroker/clientlibs_base/css/menu.css" rel="stylesheet" type="text/css"/>
<link href="https://www.commbank.com.au//etc/designs/commbroker/clientlibs_base/css/layout.css" rel="stylesheet" type="text/css"/>
<link href="https://www.commbank.com.au//etc/designs/commbroker/clientlibs_base/css/styles.css" rel="stylesheet" type="text/css"/>
<link href="https://www.commbank.com.au//etc/designs/commbroker/clientlibs_base/css/MenuPrint.css" media="print" rel="stylesheet" type="text/css"/>
<link href="https://www.commbank.com.au//etc/designs/commbroker/clientlibs_base/css/layoutPrint.css" media="print" rel="stylesheet" type="text/css"/>




<!-- SiteCatalyst code version: H.20.3.Copyright 1996-2009 Adobe, Inc. All Rights ReservedMore info available at http://www.omniture.com -->


</head>
<body>
<general>
<div id="Container">
<content>
<div id="wrapper">
<div id="content" style="position:relative;">
<div class="page_heading">
<page_heading>
<h1 class="title">Credit Policy</h1>
</page_heading>
</div>
<div class="subheading">
<sub_heading>
<h1>Eligible Income</h1>
</sub_heading>
</div>
<div class="text parbase">
<p style="text-align: right;"><span style="font-size: 10pt;"><a adhocenable="false" href="/Net/Documentum/credit-policy/eligible-income/general-requirements.aspx">Back to Eligible Income</a></span></p>
<p><span style="font-size: 10pt;"><b>Investment Income (Proposed)</b></span></p>
<p><span style="font-size: 10pt;"> </span></p>
<p><span style="font-size: 10pt;">Proposed investment income is the income to be generated by any asset (excluding rental properties) that the customer is purchasing, e.g. dividends from the purchase of shares or distribution from the purchase of managed funds.</span></p>
<p><span style="font-size: 10pt;"> </span></p>
<p><span style="font-size: 10pt;">Proposed investment income is an excluded income and will not be considered. Investment income will only be considered for existing investment holdings when the existing investment has no margin loan attached (unencumbered), refer <a href="/Net/Documentum/credit-policy/eligible-income/existing-investment-income.aspx">Investment income (Existing)</a> for details.   </span></p>
<p><span style="font-size: 10pt;"> </span></p>
<p class="MsoNormal" style="line-height: 16.8pt;"><span style="font-size: 10pt;"> </span></p>
<p> </p>
</div>
<div class="contactsTableBoxLeft">
<div class="text parbase">
</div>
</div>
<div class="contactsTableBoxRight">
<div class="text parbase">
</div>
</div>
</div>
</div>
</content>
</div>
</general>
</body>
</html>
